apiVersion: v1
kind: ConfigMap
metadata:
  name: fiscal-saas-config
  labels:
    app.kubernetes.io/part-of: fiscal-saas
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fiscal_saas
  APP_CORS_ALLOWED_ORIGINS: http://localhost:18080,http://127.0.0.1:18080
  APP_SECURITY_AUTH_MODE: demo
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/fiscal-saas
  VERIFACTU_MODE: stub
  AEAT_PRODUCTION_ENABLED: "false"
