apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiscal-saas-preprod
resources:
  - namespace.yml
  - configmap.yml
  - mysql.yml
  - backend.yml
  - frontend.yml
  - nginx.yml
  - network-policy.yml
